controller_node:
  ros__parameters:
    # LOS guidance
    U: 0.5
    Delta: 0.5
    k: 0.5

    # Pendulum/adaptive controller (keep defaults unless you know better)
    L: 3.5
    epsilon: 0.5
    k_v: 1.0
    k_a: 0.1
    m_virtual: 1.0

    # Thruster mapping
    base_thrust: 20.0
    thrust_scale: 6.0        # forward percent per controller force unit (tune)
    turn_gain: 60.0          # percent per unit yaw-control
    turn_sign: 1.0           # set to -1.0 if turning direction is reversed

    # Heading PD
    k_psi: 2.0
    k_r: 1.0

    # Safety / limits
    max_forward_percent: 30.0
    max_turn_percent: 30.0
    max_s_dot: 0.5
    max_s_init_jump: 1.0

    # Path file (relative or absolute) - adjust if you want this params file to set the path
    path_file: "$(pwd)/circle_radius_3m.yaml"
